const fs = require('fs');
const path = require('path');

function slugify(text) {
  return text.toString().toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
}

const dir = path.join(__dirname, 'src/data/dictionaries');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.ts'));

files.forEach(file => {
  const filePath = path.join(dir, file);
  let content = fs.readFileSync(filePath, 'utf8');
  
  // A bit hacky: we can use regex to find { name: '...', definition: '...' }
  // Since the files were generated by LLM, they might have slight variations, but it's valid TS.
  // Actually, let's just use a regex replace on the name field.
  // Match `name: 'Some Name'` or `name: "Some Name"`
  
  content = content.replace(/name:\s*(['"`])(.*?)\1/g, (match, quote, name) => {
    const slug = slugify(name);
    return `${match}, slug: '${slug}'`;
  });
  
  fs.writeFileSync(filePath, content);
  console.log(`Added slugs to ${file}`);
});
